cmake_minimum_required(VERSION 3.16)

project(Hatze1978Plugin LANGUAGES CXX)

set(PLUGIN_NAME "osimHatze1978Plugin" CACHE STRING
    "Name of the shared library to create")

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

find_package(OpenSim REQUIRED PATHS "${OPENSIM_INSTALL_DIR}")

file(GLOB SOURCE_FILES CONFIGURE_DEPENDS *.cpp)
file(GLOB INCLUDE_FILES CONFIGURE_DEPENDS *.h)

add_library(${PLUGIN_NAME} SHARED ${SOURCE_FILES} ${INCLUDE_FILES})
target_link_libraries(${PLUGIN_NAME} PRIVATE ${OpenSim_LIBRARIES})

set_target_properties(
    ${PLUGIN_NAME} PROPERTIES
    DEFINE_SYMBOL OSIMHATZE1978PLUGIN_EXPORTS
    PROJECT_LABEL "Libraries - ${PLUGIN_NAME}"
)
